wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1674722658
    t:
      1:
      - 1
      - 41
      - 50
      2:
      - 1
      - 41
      - 50
      3:
      - 1
      - 13
      - 16
      4: 3.9.13
      5: 0.12.11
      8:
      - 3
      - 5
batch:
  desc: null
  value: 16
data:
  desc: null
  value: training/trail22kd.yaml
entity:
  desc: null
  value: trail22kd
epochs:
  desc: null
  value: 10
name:
  desc: null
  value: walt-cam1-week5-yolov8-random-25
project:
  desc: null
  value: kdtest
weights:
  desc: null
  value: yolov8n.pt
